"""
substralink/sla/evaluator.py

Python implementation of the SubstraLink SLA Evaluation Specification v1.0.0.

This module is a conformant port of src/sla/evaluator.rs.
All behavior is governed by SLA_EVAL_SPEC_v1.0.0.md.

CRITICAL IMPLEMENTATION RULES (from spec ?9):
- All intermediate computation uses float (float64).
- All final integer outputs use math.floor() ? never round(), never ceil().
- All division is float division ? never integer division.
- Clamp: max(min_val, min(max_val, x)).
- JSON canonicalization: json.dumps(d, sort_keys=True, separators=(',', ':'))
"""

from __future__ import annotations

import json
import math
from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional


# ??? Constants (spec ?2) ??????????????????????????????????????????????????????
# DO NOT modify these without incrementing the spec version.

VIOLATION_RATIO_PASS_THRESHOLD: float = 0.0
ACS_SHARED_THRESHOLD: float = 0.65
MIN_CALLS_FOR_ATTRIBUTION: int = 3
THIN_EVIDENCE_DISCOUNT: float = 0.5
STRICTNESS_MIN: float = 0.1
STRICTNESS_MAX: float = 10.0
STAKE_RATIO_MIN: float = 0.0
STAKE_RATIO_MAX: float = 1.0
STAKE_RATIO_TOLERANCE: float = 0.001


# ??? Input Types (spec ?3) ????????????????????????????????????????????????????

@dataclass
class SlaIntent:
    """
    Parsed from the `intent` field of a SubstraLink Decision with type = "sla.v1".
    All fields required. declared_var and latency_ms must be > 0.
    """
    declared_var: int           # u64 ? max tolerated economic loss
    latency_ms: int             # u64 ? max acceptable latency per call
    strictness_multiplier: float  # f64 ? amplifies slash; clamped to [0.1, 10.0]
    dependency_depth: int       # u32 ? logged only in v1, not used in computation
    exposure_time_ms: int       # u64 ? logged only in v1, not used in computation
    provider_stake_ratio: float  # f64 ? provider's fraction of base_slash
    caller_stake_ratio: float   # f64 ? caller's fraction of base_slash

    @classmethod
    def from_dict(cls, d: dict) -> "SlaIntent":
        return cls(
            declared_var=int(d["declared_var"]),
            latency_ms=int(d["latency_ms"]),
            strictness_multiplier=float(d["strictness_multiplier"]),
            dependency_depth=int(d.get("dependency_depth", 0)),
            exposure_time_ms=int(d.get("exposure_time_ms", 0)),
            provider_stake_ratio=float(d["provider_stake_ratio"]),
            caller_stake_ratio=float(d["caller_stake_ratio"]),
        )

    def to_canonical_json(self) -> str:
        """
        Canonical JSON serialization for hashing and kernel submission.
        Keys sorted alphabetically, no whitespace, UTF-8.
        Spec ?9: json.dumps(d, sort_keys=True, separators=(',', ':'))
        """
        d = {
            "type": "sla.v1",
            "caller_stake_ratio": self.caller_stake_ratio,
            "declared_var": self.declared_var,
            "dependency_depth": self.dependency_depth,
            "exposure_time_ms": self.exposure_time_ms,
            "latency_ms": self.latency_ms,
            "provider_stake_ratio": self.provider_stake_ratio,
            "strictness_multiplier": self.strictness_multiplier,
        }
        return json.dumps(d, sort_keys=True, separators=(",", ":"))


@dataclass
class SlaProviderAttestation:
    """
    Evidence record for a single tracked call, submitted by the provider.
    Serialized as JSON in the `reasoning` field of a SubstraLink Attestation.
    """
    call_id: str
    timestamp: int
    request_hash: str
    response_hash: str
    latency_ms: int
    status_code: int
    correctness_passed: bool

    @classmethod
    def from_dict(cls, d: dict) -> "SlaProviderAttestation":
        return cls(
            call_id=str(d["call_id"]),
            timestamp=int(d["timestamp"]),
            request_hash=str(d["request_hash"]),
            response_hash=str(d["response_hash"]),
            latency_ms=int(d["latency_ms"]),
            status_code=int(d["status_code"]),
            correctness_passed=bool(d["correctness_passed"]),
        )

    def to_dict(self) -> dict:
        return {
            "call_id": self.call_id,
            "timestamp": self.timestamp,
            "request_hash": self.request_hash,
            "response_hash": self.response_hash,
            "latency_ms": self.latency_ms,
            "status_code": self.status_code,
            "correctness_passed": self.correctness_passed,
        }


@dataclass
class SlaCallerAttestation:
    """
    Evidence record submitted by the caller (auto-generated by SDK in v1).
    Serialized as JSON in the `reasoning` field of a caller Attestation.
    """
    call_id: str
    request_well_formed: bool
    declared_var_mismatch: bool

    @classmethod
    def from_dict(cls, d: dict) -> "SlaCallerAttestation":
        return cls(
            call_id=str(d["call_id"]),
            request_well_formed=bool(d["request_well_formed"]),
            declared_var_mismatch=bool(d["declared_var_mismatch"]),
        )


@dataclass
class SlaAttestationBundle:
    provider_calls: List[SlaProviderAttestation] = field(default_factory=list)
    caller_calls: List[SlaCallerAttestation] = field(default_factory=list)


# ??? Output Types (spec ?4) ???????????????????????????????????????????????????

class OutcomeType(str, Enum):
    SLA_PASS = "SlaPass"
    SLA_SLASH_PROVIDER = "SlaSlashProvider"
    SLA_SLASH_CALLER = "SlaSlashCaller"
    SLA_SHARED_SLASH = "SlaSharedSlash"


@dataclass
class ResolveOutcome:
    """
    Mirrors the Rust ResolveOutcome enum SLA variants.
    Use the class methods to construct, not the constructor directly.
    """
    outcome_type: OutcomeType
    amount: Optional[int] = None            # SlaSlashProvider, SlaSlashCaller
    provider_amount: Optional[int] = None   # SlaSharedSlash
    caller_amount: Optional[int] = None     # SlaSharedSlash

    @classmethod
    def sla_pass(cls) -> "ResolveOutcome":
        return cls(outcome_type=OutcomeType.SLA_PASS)

    @classmethod
    def sla_slash_provider(cls, amount: int) -> "ResolveOutcome":
        return cls(outcome_type=OutcomeType.SLA_SLASH_PROVIDER, amount=amount)

    @classmethod
    def sla_slash_caller(cls, amount: int) -> "ResolveOutcome":
        return cls(outcome_type=OutcomeType.SLA_SLASH_CALLER, amount=amount)

    @classmethod
    def sla_shared_slash(cls, provider_amount: int, caller_amount: int) -> "ResolveOutcome":
        return cls(
            outcome_type=OutcomeType.SLA_SHARED_SLASH,
            provider_amount=provider_amount,
            caller_amount=caller_amount,
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, ResolveOutcome):
            return False
        if self.outcome_type != other.outcome_type:
            return False
        if self.outcome_type == OutcomeType.SLA_PASS:
            return True
        if self.outcome_type in (OutcomeType.SLA_SLASH_PROVIDER, OutcomeType.SLA_SLASH_CALLER):
            return self.amount == other.amount
        if self.outcome_type == OutcomeType.SLA_SHARED_SLASH:
            return (self.provider_amount == other.provider_amount and
                    self.caller_amount == other.caller_amount)
        return False

    def to_dict(self) -> dict:
        if self.outcome_type == OutcomeType.SLA_PASS:
            return {"type": "SlaPass"}
        if self.outcome_type == OutcomeType.SLA_SLASH_PROVIDER:
            return {"type": "SlaSlashProvider", "data": {"amount": self.amount}}
        if self.outcome_type == OutcomeType.SLA_SLASH_CALLER:
            return {"type": "SlaSlashCaller", "data": {"amount": self.amount}}
        if self.outcome_type == OutcomeType.SLA_SHARED_SLASH:
            return {"type": "SlaSharedSlash", "data": {
                "provider_amount": self.provider_amount,
                "caller_amount": self.caller_amount,
            }}
        raise ValueError(f"Unknown outcome type: {self.outcome_type}")

    @property
    def label(self) -> str:
        labels = {
            OutcomeType.SLA_PASS: "PASS",
            OutcomeType.SLA_SLASH_PROVIDER: "SLASH_PROVIDER",
            OutcomeType.SLA_SLASH_CALLER: "SLASH_CALLER",
            OutcomeType.SLA_SHARED_SLASH: "SHARED_SLASH",
        }
        return labels[self.outcome_type]


@dataclass
class SlaEvaluationResult:
    outcome: ResolveOutcome
    provider_slash: int
    caller_slash: int
    violation_count: int
    total_calls: int
    latency_violation_count: int
    correctness_violation_count: int
    caller_fault_count: int
    attribution_confidence: float
    reason_summary: str


# ??? Intent Validation (spec ?7) ?????????????????????????????????????????????

def validate_intent(intent: SlaIntent) -> None:
    """
    Validates SlaIntent fields. Raises ValueError with a descriptive message
    on the first failing check. Checks run in spec-defined order.
    """
    ratio_sum = intent.provider_stake_ratio + intent.caller_stake_ratio
    if abs(ratio_sum - 1.0) > STAKE_RATIO_TOLERANCE:
        raise ValueError(
            f"stake ratios must sum to 1.0, got {ratio_sum:.4f}"
        )
    if intent.strictness_multiplier <= 0.0:
        raise ValueError("strictness_multiplier must be positive")
    if intent.latency_ms == 0:
        raise ValueError("latency_ms must be non-zero")
    if intent.declared_var == 0:
        raise ValueError("declared_var must be > 0")


# ??? Risk Signal (spec ?6) ????????????????????????????????????????????????????

def severity_from_slash(slash_amount: int, declared_var: int) -> float:
    """
    Normalized severity in [0.0, 1.0] for risk signal emission.
    spec ?6: CLAMP(slash_amount / declared_var, 0.0, 1.0)
    """
    if declared_var == 0:
        return 0.0
    return max(0.0, min(1.0, slash_amount / declared_var))


# ??? Core Evaluator (spec ?5) ?????????????????????????????????????????????????

def evaluate_sla(
    intent: SlaIntent,
    bundle: SlaAttestationBundle,
) -> SlaEvaluationResult:
    """
    Deterministic SLA evaluation. Pure function ? no I/O, no side effects.

    Implements the evaluation pipeline defined in spec ?5, Steps 0?8.
    MUST produce identical outputs to the Rust implementation for all inputs.

    Rounding: math.floor() for all integer outputs. Never round(), never ceil().
    Division: always float division.
    """

    # ?? Step 0: Empty bundle guard ????????????????????????????????????????????
    if not bundle.provider_calls:
        return SlaEvaluationResult(
            outcome=ResolveOutcome.sla_pass(),
            provider_slash=0,
            caller_slash=0,
            violation_count=0,
            total_calls=0,
            latency_violation_count=0,
            correctness_violation_count=0,
            caller_fault_count=0,
            attribution_confidence=1.0,
            reason_summary="No calls recorded. Session passes vacuously.",
        )

    # ?? Step 1: Count provider-side violations ????????????????????????????????
    total_calls: int = len(bundle.provider_calls)

    latency_violations: int = sum(
        1 for c in bundle.provider_calls
        if c.latency_ms > intent.latency_ms
    )

    correctness_violations: int = sum(
        1 for c in bundle.provider_calls
        if not c.correctness_passed
    )

    provider_violation_count: int = latency_violations + correctness_violations

    # ?? Step 2: Count caller-side faults ?????????????????????????????????????
    if not bundle.caller_calls:
        caller_fault_count: int = 0
    else:
        caller_fault_count = sum(
            1 for c in bundle.caller_calls
            if not c.request_well_formed or c.declared_var_mismatch
        )

    # ?? Step 3: Pass check ????????????????????????????????????????????????????
    total_fault_signals: int = provider_violation_count + caller_fault_count

    if total_fault_signals == 0:
        return SlaEvaluationResult(
            outcome=ResolveOutcome.sla_pass(),
            provider_slash=0,
            caller_slash=0,
            violation_count=0,
            total_calls=total_calls,
            latency_violation_count=latency_violations,
            correctness_violation_count=correctness_violations,
            caller_fault_count=0,
            attribution_confidence=1.0,
            reason_summary=(
                f"All {total_calls} calls passed SLA. No violations detected."
            ),
        )

    # ?? Step 4: Violation ratio and base slash ????????????????????????????????
    # Float division ? spec ?9
    violation_ratio: float = provider_violation_count / total_calls

    strictness: float = max(STRICTNESS_MIN, min(STRICTNESS_MAX, intent.strictness_multiplier))

    base_slash: int = math.floor(intent.declared_var * violation_ratio * strictness)

    # ?? Step 5: Attribution confidence ???????????????????????????????????????
    # Float division ? total_fault_signals guaranteed > 0 here
    provider_weight: float = provider_violation_count / total_fault_signals
    caller_weight: float   = caller_fault_count       / total_fault_signals

    raw_confidence: float = abs(provider_weight - caller_weight)

    if total_calls < MIN_CALLS_FOR_ATTRIBUTION:
        confidence: float = raw_confidence * THIN_EVIDENCE_DISCOUNT
    else:
        confidence = raw_confidence

    # ?? Step 6: Slash split ???????????????????????????????????????????????????
    provider_ratio: float = max(STAKE_RATIO_MIN, min(STAKE_RATIO_MAX, intent.provider_stake_ratio))
    caller_ratio: float   = max(STAKE_RATIO_MIN, min(STAKE_RATIO_MAX, intent.caller_stake_ratio))

    provider_slash: int = math.floor(base_slash * provider_ratio * provider_weight)
    caller_slash: int   = math.floor(base_slash * caller_ratio   * caller_weight)

    # ?? Step 7: Outcome variant ???????????????????????????????????????????????
    if confidence < ACS_SHARED_THRESHOLD:
        outcome = ResolveOutcome.sla_shared_slash(
            provider_amount=provider_slash,
            caller_amount=caller_slash,
        )
    elif provider_weight >= caller_weight:
        if caller_slash == 0:
            outcome = ResolveOutcome.sla_slash_provider(amount=provider_slash)
        else:
            outcome = ResolveOutcome.sla_shared_slash(
                provider_amount=provider_slash,
                caller_amount=caller_slash,
            )
    else:
        if provider_slash == 0:
            outcome = ResolveOutcome.sla_slash_caller(amount=caller_slash)
        else:
            outcome = ResolveOutcome.sla_shared_slash(
                provider_amount=provider_slash,
                caller_amount=caller_slash,
            )

    # ?? Step 8: Reason summary ????????????????????????????????????????????????
    reason_summary = (
        f"{outcome.label} | calls={total_calls} "
        f"provider_violations={provider_violation_count} "
        f"(latency={latency_violations} correctness={correctness_violations}) "
        f"caller_faults={caller_fault_count} "
        f"provider_slash={provider_slash} "
        f"caller_slash={caller_slash} "
        f"confidence={confidence:.2f}"
    )

    return SlaEvaluationResult(
        outcome=outcome,
        provider_slash=provider_slash,
        caller_slash=caller_slash,
        violation_count=provider_violation_count,
        total_calls=total_calls,
        latency_violation_count=latency_violations,
        correctness_violation_count=correctness_violations,
        caller_fault_count=caller_fault_count,
        attribution_confidence=confidence,
        reason_summary=reason_summary,
    )


# ??? Reference Test Vectors (spec ?8) ????????????????????????????????????????
# Run with: python -m pytest substralink/sla/evaluator.py -v
# Or: python substralink/sla/evaluator.py

def _base_intent() -> SlaIntent:
    return SlaIntent(
        declared_var=1000,
        latency_ms=200,
        strictness_multiplier=1.5,
        dependency_depth=2,
        exposure_time_ms=5000,
        provider_stake_ratio=0.9,
        caller_stake_ratio=0.1,
    )


def _run_reference_tests() -> None:
    import sys

    failures = []

    def check(name: str, got, expected, tolerance: float = 0.0):
        if isinstance(expected, float) and tolerance > 0:
            if abs(got - expected) > tolerance:
                failures.append(f"  FAIL {name}: got {got!r}, expected {expected!r}")
        elif got != expected:
            failures.append(f"  FAIL {name}: got {got!r}, expected {expected!r}")

    intent = _base_intent()

    # ?? Vector 1: Empty bundle ????????????????????????????????????????????????
    r = evaluate_sla(intent, SlaAttestationBundle())
    check("v1.outcome", r.outcome.outcome_type, OutcomeType.SLA_PASS)
    check("v1.provider_slash", r.provider_slash, 0)
    check("v1.total_calls", r.total_calls, 0)
    check("v1.confidence", r.attribution_confidence, 1.0)

    # ?? Vector 2: All calls pass ??????????????????????????????????????????????
    r = evaluate_sla(intent, SlaAttestationBundle(
        provider_calls=[
            SlaProviderAttestation("c1", 0, "a", "b", 100, 200, True),
            SlaProviderAttestation("c2", 0, "a", "b", 150, 200, True),
            SlaProviderAttestation("c3", 0, "a", "b", 199, 200, True),
        ]
    ))
    check("v2.outcome", r.outcome.outcome_type, OutcomeType.SLA_PASS)
    check("v2.violation_count", r.violation_count, 0)
    check("v2.total_calls", r.total_calls, 3)

    # ?? Vector 3: Single latency violation, 4 calls, clean caller ????????????
    r = evaluate_sla(intent, SlaAttestationBundle(
        provider_calls=[
            SlaProviderAttestation("c1", 0, "a", "b", 300, 200, True),
            SlaProviderAttestation("c2", 0, "a", "b", 100, 200, True),
            SlaProviderAttestation("c3", 0, "a", "b", 100, 200, True),
            SlaProviderAttestation("c4", 0, "a", "b", 100, 200, True),
        ],
        caller_calls=[
            SlaCallerAttestation("c1", True, False),
        ]
    ))
    check("v3.outcome_type", r.outcome.outcome_type, OutcomeType.SLA_SLASH_PROVIDER)
    check("v3.provider_slash", r.provider_slash, 337)
    check("v3.caller_slash", r.caller_slash, 0)
    check("v3.violation_count", r.violation_count, 1)
    check("v3.total_calls", r.total_calls, 4)
    check("v3.confidence", r.attribution_confidence, 1.0, tolerance=0.0001)

    # ?? Vector 4: Thin evidence ???????????????????????????????????????????????
    r = evaluate_sla(intent, SlaAttestationBundle(
        provider_calls=[
            SlaProviderAttestation("c1", 0, "a", "b", 400, 200, True),
        ],
        caller_calls=[
            SlaCallerAttestation("c1", True, False),
        ]
    ))
    check("v4.outcome_type", r.outcome.outcome_type, OutcomeType.SLA_SHARED_SLASH)
    check("v4.provider_slash", r.provider_slash, 1350)
    check("v4.caller_slash", r.caller_slash, 0)
    check("v4.confidence", r.attribution_confidence, 0.5, tolerance=0.0001)

    # ?? Vector 5: Mixed fault ?????????????????????????????????????????????????
    r = evaluate_sla(intent, SlaAttestationBundle(
        provider_calls=[
            SlaProviderAttestation("c1", 0, "a", "b", 300, 200, True),
            SlaProviderAttestation("c2", 0, "a", "b", 100, 200, True),
            SlaProviderAttestation("c3", 0, "a", "b", 100, 200, True),
            SlaProviderAttestation("c4", 0, "a", "b", 100, 200, True),
            SlaProviderAttestation("c5", 0, "a", "b", 100, 200, True),
        ],
        caller_calls=[
            SlaCallerAttestation("c1", False, False),
        ]
    ))
    check("v5.outcome_type", r.outcome.outcome_type, OutcomeType.SLA_SHARED_SLASH)
    check("v5.provider_slash", r.provider_slash, 135)
    check("v5.caller_slash", r.caller_slash, 15)
    check("v5.confidence", r.attribution_confidence, 0.0, tolerance=0.0001)

    # ?? Vector 6: Severity helper ?????????????????????????????????????????????
    check("v6.sev_337", severity_from_slash(337, 1000), 0.337, tolerance=0.0001)
    check("v6.sev_0", severity_from_slash(0, 1000), 0.0)
    check("v6.sev_1000", severity_from_slash(1000, 1000), 1.0)
    check("v6.sev_clamp", severity_from_slash(2000, 1000), 1.0)
    check("v6.sev_zero_denom", severity_from_slash(500, 0), 0.0)

    # ?? Vector 7: Intent validation ???????????????????????????????????????????
    try:
        validate_intent(_base_intent())
        check("v7.valid_ok", True, True)
    except ValueError:
        failures.append("  FAIL v7.valid_ok: raised unexpectedly")

    for bad_intent, label in [
        (SlaIntent(1000, 200, 1.5, 2, 5000, 0.8, 0.8), "v7.bad_ratios"),
        (SlaIntent(1000, 200, 0.0, 2, 5000, 0.9, 0.1), "v7.bad_strictness"),
        (SlaIntent(1000, 0,   1.5, 2, 5000, 0.9, 0.1), "v7.bad_latency"),
        (SlaIntent(0,    200, 1.5, 2, 5000, 0.9, 0.1), "v7.bad_var"),
    ]:
        try:
            validate_intent(bad_intent)
            failures.append(f"  FAIL {label}: expected ValueError, none raised")
        except ValueError:
            pass  # expected

    # ?? Report ????????????????????????????????????????????????????????????????
    if failures:
        print("REFERENCE VECTOR FAILURES:")
        for f in failures:
            print(f)
        sys.exit(1)
    else:
        print(f"All reference test vectors passed. ({7} vectors)")


if __name__ == "__main__":
    _run_reference_tests()
